### ISSUE TITLE
Update config schema for cover

### ISSUE THREAD

**Issue by cschwartz** [cschwartz/home-assistant-custom-components-eltako#4]
Cover config schema should use key/value pairs for traveling time and tilting time.
While traveling time should be a required field, tilting time should be optional.
The target configuration schema should be:
- for a cover not supporting tilts:
```yaml
  - platform: eltako
    devices:
      cover_id
        name: "My Not Tilting Cover
        virtual_switch:
          id: "input_select.e2m_og_my_virtual_switch_action"
        switch_listeners:
          switch_1:
            position: left
            is_inverted: yes
          main_switch: {}
        traveling_time:
          up: 18
          down: 18
```
- for a cover supporting tilts:
```yaml
  - platform: eltako
    devices:
      cover_id
        name: "My Tilting Cover
        virtual_switch:
          id: "input_select.e2m_og_my_virtual_switch_action"
        switch_listeners:
          switch_1:
            position: left
            is_inverted: yes
          main_switch: {}
        traveling_time:
          up: 18
          down: 18
        tiling_time:
          up: 18
          down: 18
```
